---

- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: restart ad
  service:
    name: samba-ad-dc
    state: restarted

- name: restart dhcp
  service:
    name: isc-dhcp-server
    state: restarted
