---

- name: Ensure NTP server is installed
  apt:
    name: ntp
    state: present

- name: Copy NTP configuration
  copy: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Ensure firewall permits NTP traffic
  ufw:
    rule: allow
    proto: udp
    port: '123'
    comment: NTP

- name: Ensure NTP service is running
  service:
    name: ntp
    state: started

