---

- name: Ensure PXE packages are installed
  apt:
    name:
    - dnsmasq
    - pxelinux
    state: present

- name: Ensure dnsmasq is configured as a DHCP proxy server
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Ensure tftpboot file tree exists
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory

- name: Create network boot menu
  copy:
    src: default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default

- name: Ensure pxelinux is available
  file:
    path: /var/lib/tftpboot/pxelinux.0
    src: /usr/lib/PXELINUX/pxelinux.0
    state: link

- name: Ensure memdisk kernel is available
  file:
    path: /var/lib/tftpboot/memdisk
    src: /usr/lib/syslinux/memdisk
    state: link

- name: Ensure syslinux modules are available
  file:
    path: /var/lib/tftpboot/{{item}}.c32
    src: /usr/lib/syslinux/modules/bios/{{item}}.c32
    state: link
  with_items:
    - ldlinux
    - menu
    - libcom32
    - libutil

- name: Ensure dnsmasq service is enabled
  service:
    name: dnsmasq
    enabled: yes
    state: started

- name: Ensure firewall permits Bootstrap Protocol (BOOTP)
  ufw:
    rule: allow
    proto: udp
    port: '67'
    comment: BOOTP

- name: Ensure firewall permits TFTP
  ufw:
    rule: allow
    proto: udp
    port: '69'
    comment: TFTP

- name: Ensure firewall permits proxyDHCP
  ufw:
    rule: allow
    proto: udp
    port: '4011'
    comment: proxyDHCP

