---

- name: Configure IP networking
  import_tasks: network.yml

- name: Install dependencies
  import_tasks: deps.yml

# We have to wait till now to update fqdn because ansible needs
# the python-netaddr plugin
- name: Configure fqdn
  template: src=hosts.j2 dest=/etc/hosts

- name: Configure firewall
  import_tasks: firewall.yml
