---

- name: Determine if DNS is running locally
  stat:
    path: /etc/systemd/system/multi-user.target.wants/bind9.service
  register: local_dns

- name: Configure network adapter
  template: src=01-netcfg.yaml.j2 dest=/etc/netplan/01-netcfg.yaml
  register: network_setting

- name: Apply network configuration
  command: netplan apply
  when: network_setting is changed

- name: Configure hostname
  template: src=hostname.j2 dest=/etc/hostname
  register: hostname_setting

- name: Run ubuntu hostname config command
  command: hostnamectl set-hostname {{hostname}}
  when: hostname_setting is changed
