---

- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: restart ad
  service:
    name: samba-ad-dc
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted

