---

- name: Ensure Samba is installed
  apt:
    name:
    - acl
    - attr
    - apparmor-utils
    - dnsutils
    - samba
    - samba-dsdb-modules
    - samba-vfs-modules
    - smbclient
    - winbind
    - libpam-winbind
    - libnss-winbind
    - libpam-krb5
    - krb5-config
    - krb5-user
    state: present
