---

- name: Install Samba
  import_tasks: install.yml

- name: Check to see whether samba is already configured
  lineinfile:
    name: /etc/samba/smb.conf
    regexp: 'server role = standalone server'
    line: ''
    state: present
    create: yes
  check_mode: yes
  register: unconfigured

- name: Provision Active Directory
  import_tasks: provision.yml
  when: unconfigured.changed

- name: Configure DNS
  import_tasks: dns.yml

- name: Configure NTP
  import_tasks: ntp.yml

- name: Ensure Kerberos is configured
  copy:
    remote_src: yes
    src: /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    group: bind

- name: Restart Bind9 and NTP before enabling AD service if domain was just configured
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - bind9
    - ntp
  when: unconfigured.changed

- name: Ensure Firewall Permits SMB, LDAP, and Kerberos Traffic
  import_tasks: firewall.yml

- name: Ensure Samba active directory service is enabled and running
  service:
    name: samba-ad-dc
    state: started
    enabled: yes
    masked: no

- name: Ensure DNS Reverse Lookup
  import_tasks: reverse_lookup.yml

- name: Ensure CA Root Trust by Windows Domain Members
  import_tasks: ca_root_trust.yml
  when: "'ca' in ansible_play_role_names"

# Possible troubleshooting step:  sudo net cache flush
#
# Might have to unmask service:  sudo systemctl unmask samba-ad-dc
#
# Verify services are running:  ps axf | egrep "samba|smbd|winbindd"
# 
# Verify DNS:
#   _ldap SRV record:  host -t SRV _ldap._tcp.samdom.example.com.
#   _kerberos SRV record:  host -t SRV _kerberos._udp.samdom.example.com.
#   A record for DC:  host -t A dc1.samdom.example.com.
# 
# Verifying file server shares:  smbclient -L localhost -U%
#   Should see netlogon, sysvol, and IPC$
# 
# To verify logon share authentication using domain admin account:
#   smbclient //localhost/netlogon -UAdministrator -c 'ls'
#
# Get ports for firewall:  sudo netstat –tulpn| egrep ‘smbd|samba’
#
# Show domain level:  sudo samba-tool domain level show
#
# Test kerberos auth:  kinit administrator@TECMINT.LAN
# List kerberos tickets:  klist
