---

- hosts: localhost
  module_defaults:
    apt:
      force_apt_get: yes
  become: yes
  vars_files:
    - env.yml
  roles:
  - role: common
  - role: ntp
  - role: dns
  - role: active_directory

