---
- hosts: all
  vars_files:
    - env.yml

  module_defaults:
    apt:
      force_apt_get: yes

  tasks:
    - name: Update ubuntu
      apt:
        update_cache: yes
#        upgrade: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      ignore_errors: yes

    - name: Clean up old packages and files to save space
      apt:
        autoclean: yes
        autoremove: yes

    - name: Install ansible
      apt:
        name: ansible
        state: present

